name: kinfu
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_2
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1m=h7f8727e_0
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.2.4=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.2=py39_cu113
  - torchvision=0.11.3=py39_cu113
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - addict==2.4.0
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - black==22.1.0
    - bleach==4.1.0
    - cffi==1.15.0
    - charset-normalizer==2.0.11
    - click==8.0.3
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.4
    - executing==0.8.2
    - fonttools==4.29.1
    - idna==3.3
    - imageio==2.14.1
    - ipykernel==6.8.0
    - ipython==8.0.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - jupyter-packaging==0.11.1
    - jupyter-server==1.13.5
    - jupyterlab==3.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbclassic==0.3.5
    - nbclient==0.5.10
    - nbconvert==6.4.1
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - notebook==6.4.8
    - open3d==0.14.1
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pandas==1.4.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.4.1
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.26
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.2.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - requests==2.27.1
    - scikit-image==0.19.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - send2trash==1.8.0
    - sniffio==1.2.0
    - stack-data==0.1.4
    - terminado==0.13.1
    - testpath==0.5.0
    - threadpoolctl==3.1.0
    - tifffile==2022.2.2
    - tomli==2.0.0
    - tomlkit==0.9.0
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.1
    - trimesh==3.9.43
    - urllib3==1.26.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - widgetsnbextension==3.5.2
